import type { Metadata } from 'next';
import './globals.css';
import ThemeToggle from './components/ThemeToggle';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

// Runs before first paint: explicit choice from localStorage wins, else system preference.
const themeInitScript = `
try {
    const stored = localStorage.getItem('theme');
    const dark = stored === 'dark' || (stored !== 'light' && matchMedia('(prefers-color-scheme: dark)').matches);
    if (dark) document.documentElement.classList.add('dark');
} catch {}
`;

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" suppressHydrationWarning data-oid="6nvi4s1">
            <head>
                <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
            </head>
            <body className="antialiased" data-oid="g6y.kn_">
                <ThemeToggle />
                {children}
            </body>
        </html>
    );
}
